{% set name = "felupe" %}
{% set version = "9.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/felupe-{{ version }}.tar.gz
  sha256: 02a661b2cb3d0b769879ac758bb6dec78a179e29c4a132b7936df706e5cee061

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  imports:
    - felupe
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/felupe/
  summary: Finite Element Analysis
  dev_url: https://github.com/adtzlr/felupe
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adtzlr
