{% set name = "felupe" %}
{% set version = "11.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/felupe-{{ version }}.tar.gz
  sha256: 447ec1f2f620bcef3e6fca44e04f3a71d8b7fe69056d264eea96e2fb5c0c0810

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  imports:
    - felupe
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/felupe/
  summary: Finite Element Analysis
  dev_url: https://github.com/adtzlr/felupe
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adtzlr
