{% set name = "felupe" %}
{% set version = "10.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/felupe-{{ version }}.tar.gz
  sha256: 7da8a5b85391155b6a62b9b9a7a43994ac39cce43e5d868a477d47fdf0af7fe0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  imports:
    - felupe
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/felupe/
  summary: Finite Element Analysis
  dev_url: https://github.com/adtzlr/felupe
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adtzlr
